#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -p "plugins/dotbot-sudo/sudo.py" \
    -p "plugins/dotbot-git/git.py" \
    -p "plugins/dotbot-flatpak/flatpak.py" \
    -p "plugins/dotbot-snap/snap.py" \
    -d "${BASEDIR}" \
    -c "${CONFIG}" \
    "${@}"


#    -p "plugins/dotbot_plugin_aptget/aptget.py" \
 
